window.XY_VOTE = {
  classOptions: ['Talent A1+', 'Talent A2', 'Talent A2+'],
  unlockedTopicNumber: null,
  templates: {
    OPINION: [
      { id: 'opinion', labelEn: '1. My Opinion', labelZh: '我的观点' },
      { id: 'reason', labelEn: '2. The Reason', labelZh: '原因' },
      { id: 'example', labelEn: '3. For Example', labelZh: '举个例子' },
      { id: 'conclusion', labelEn: '4. Conclusion', labelZh: '总结' },
    ],
    STORY: [
      { id: 'story', labelEn: '1. My Story / Experience', labelZh: '我的经历' },
      { id: 'feeling', labelEn: '2. How I Felt', labelZh: '我的感受' },
      { id: 'lesson', labelEn: '3. What I Learned', labelZh: '我学到了什么' },
    ],
    IMAGINATION: [
      { id: 'imagination', labelEn: '1. My Imagination', labelZh: '我的想象' },
      { id: 'interesting', labelEn: '2. Why it is interesting', labelZh: '为什么这很有趣' },
      { id: 'next', labelEn: '3. What happens next', labelZh: '接下来会发生什么' },
    ],
  },
  topics: [
    { topicNumber: 1, titleEn: 'Should primary school students use AI to do their homework?', titleZh: '小学生该不该用 AI 写作业？', topicType: 'OPINION' },
    { topicNumber: 2, titleEn: 'AI is smart, but does it care about people?', titleZh: 'AI 很聪明，但它会关心人吗？', topicType: 'OPINION' },
    { topicNumber: 3, titleEn: 'If I had a robot classmate', titleZh: '如果我有一个机器人同学', topicType: 'IMAGINATION' },
    { topicNumber: 4, titleEn: "Why can't we stop watching short videos?", titleZh: '为什么刷短视频停不下来？', topicType: 'OPINION' },
    { topicNumber: 5, titleEn: 'Do you want to live on Mars?', titleZh: '你想住在火星吗？', topicType: 'OPINION' },
    { topicNumber: 6, titleEn: 'Curiosity is my superpower', titleZh: '好奇心是我的超能力', topicType: 'STORY' },
    { topicNumber: 7, titleEn: "A good class isn't necessarily a quiet class", titleZh: '好课堂不一定是安静的课堂', topicType: 'OPINION' },
    { topicNumber: 8, titleEn: 'Mistakes help me learn', titleZh: '错误帮助我学习', topicType: 'STORY' },
    { topicNumber: 9, titleEn: 'The best teacher is not necessarily the strictest teacher', titleZh: '最好的老师不一定是最严厉的老师', topicType: 'OPINION' },
    { topicNumber: 10, titleEn: 'Why do Chinese people value learning?', titleZh: '为什么中国人重视学习？', topicType: 'OPINION' },
    { topicNumber: 11, titleEn: 'The moment I stopped being afraid to speak English', titleZh: '我不再害怕开口说英语，是从哪一刻开始的', topicType: 'STORY' },
    { topicNumber: 12, titleEn: 'If animals could talk, whose English would be the best?', titleZh: '如果动物会说话，谁的英语最好', topicType: 'IMAGINATION' },
    { topicNumber: 13, titleEn: 'If there were only 6 hours in a day, what time would I cut?', titleZh: '如果一天只有6个小时，我会砍掉哪段时间', topicType: 'IMAGINATION' },
    { topicNumber: 14, titleEn: 'If you could delete one emotion, which one would it be?', titleZh: '如果可以删掉一种情绪，你会删哪个', topicType: 'IMAGINATION' },
    { topicNumber: 15, titleEn: 'If colors had flavors, what would red taste like?', titleZh: '如果颜色有味道，红色是什么味', topicType: 'IMAGINATION' },
    { topicNumber: 16, titleEn: "Why do adults always say \"I've told you this before\"?", titleZh: '为什么大人总说"我跟你讲过了"', topicType: 'STORY' },
    { topicNumber: 17, titleEn: 'Why does my mom believe health articles on Moments?', titleZh: '为什么我妈相信朋友圈里的养生文章', topicType: 'OPINION' },
    { topicNumber: 18, titleEn: 'Is it better to have more friends? Does a quiet child mean no ideas?', titleZh: '朋友越多越好吗？安静的孩子，就是没想法吗', topicType: 'OPINION' },
    { topicNumber: 19, titleEn: 'What is "true intelligence"?', titleZh: '什么才算"真正的聪明"', topicType: 'OPINION' },
    { topicNumber: 20, titleEn: 'Is time fair?', titleZh: '时间是公平的吗', topicType: 'OPINION' },
    { topicNumber: 21, titleEn: 'If I were to design a school, what would it look like?', titleZh: '如果让我设计一所学校，它会是什么样', topicType: 'IMAGINATION' },
    { topicNumber: 22, titleEn: 'In the animal world, who lives the smartest?', titleZh: '动物世界里，谁活得最聪明', topicType: 'OPINION' },
    { topicNumber: 23, titleEn: "Not being able to do it doesn't mean you can't do it well", titleZh: '做不到，不等于做不好', topicType: 'STORY' },
    { topicNumber: 24, titleEn: 'Growing up, what does it actually mean to become?', titleZh: '长大，到底是变成什么样', topicType: 'STORY' },
    { topicNumber: 25, titleEn: 'Why do people need friends?', titleZh: '为什么人需要朋友？', topicType: 'OPINION' },
    { topicNumber: 26, titleEn: 'If I could invent a magical app, what would it do?', titleZh: '如果我能发明一个神奇的 App，它会有什么用？', topicType: 'IMAGINATION' },
    { topicNumber: 27, titleEn: 'Will playing video games make us smarter or dumber?', titleZh: '打游戏会让我们变聪明还是变笨？', topicType: 'OPINION' },
    { topicNumber: 28, titleEn: 'A time I chose to be brave instead of perfect', titleZh: '有一次，我选择了勇敢而不是完美', topicType: 'STORY' },
    { topicNumber: 29, titleEn: 'Why do we sometimes feel angry for no reason?', titleZh: '为什么我们有时候会无缘无故地生气？', topicType: 'OPINION' },
    { topicNumber: 30, titleEn: 'What I wish adults understood about being a kid today', titleZh: '我希望大人能明白，现在做个小孩是什么感觉', topicType: 'OPINION' },
    { topicNumber: 31, titleEn: 'What makes a true friend different from a normal classmate?', titleZh: '真正的朋友和普通的同学有什么区别？', topicType: 'OPINION' },
    { topicNumber: 32, titleEn: 'The best apology I ever gave or received', titleZh: '我道过最棒的歉，或者收到过最棒的道歉', topicType: 'STORY' },
    { topicNumber: 33, titleEn: 'If history classes were taught by time machines', titleZh: '如果历史课是用时光机来上的', topicType: 'IMAGINATION' },
    { topicNumber: 34, titleEn: 'What if we had to pay for things with kindness instead of money?', titleZh: '如果买东西不用钱，而是用“善良”来支付会怎样？', topicType: 'IMAGINATION' },
    { topicNumber: 35, titleEn: 'The most useless thing I learned this year, and why I still like it', titleZh: '今年我学到的最没用的一件事，以及为什么我依然喜欢它', topicType: 'STORY' },
  ],
};
